CREATE TABLE IF NOT EXISTS STUDENT(
NO VARCHAR(10) NOT NULL PRIMARY KEY,
NAME VARCHAR(10) DEFAULT NULL,
ENT_YEAR INT DEFAULT NULL,
CLASS_NUM CHAR(5) DEFAULT NULL,
IS_ATTEND BOOL DEFAULT NULL,
SCHOOL_CD CHAR(6) DEFAULT NULL
);
