drop table TEST if exists;

CREATE TABLE TEST (
    STUDENT_NO VARCHAR(10) NOT NULL,
    SUBJECT_CD CHAR(3) NOT NULL,
    SCHOOL_CD CHAR(10) NOT NULL,
    NO INTEGER NOT NULL,
    POINT INTEGER DEFAULT NULL,
    CLASS_NUM VARCHAR(5) DEFAULT NULL,
    PRIMARY KEY (STUDENT_NO, SUBJECT_CD, NO)
);

INSERT INTO TEST (STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES ('2231111', 'A02', 'oom', 1, 100, '131')